apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ollama-claude-proxy.fullname" . }}
  labels:
    {{- include "ollama-claude-proxy.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "port": "{{ .Values.service.port }}",
      "api_version": "{{ .Values.config.apiVersion }}",
      "api_endpoint": "{{ .Values.config.apiEndpoint }}",
      "system_prompt": "{{ .Values.config.systemPrompt }}",
      "default_model": "{{ .Values.config.defaultModel }}",
      "request_timeout_secs": {{ .Values.config.requestTimeoutSecs }}
    }